//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanPickleball_65132651.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGGIA
    {
        public string MAGIA { get; set; }
        public string MALOAISAN { get; set; }
        public System.DateTime NGAYDIEUCHINH { get; set; }
        public string THU { get; set; }
        public System.TimeSpan GIOBATDAU { get; set; }
        public System.TimeSpan GIOKETTHUC { get; set; }
        public decimal GIACODINH { get; set; }
        public decimal GIAVANGLAI { get; set; }
    
        public virtual LOAISAN LOAISAN { get; set; }
    }
}
