//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanPickleball_65132651.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDICHVUDAT
    {
        public string MADV { get; set; }
        public string MAPHIEUDAT { get; set; }
        public int SOLUONG { get; set; }
        public decimal DONGIA { get; set; }
        public decimal THANHTIEN { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual PHIEUDATSAN PHIEUDATSAN { get; set; }
    }
}
