//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanPickleball_65132651.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICHVU()
        {
            this.CHITIETDICHVUDAT = new HashSet<CHITIETDICHVUDAT>();
        }
    
        public string MADV { get; set; }
        public string TENDV { get; set; }
        public string LOAIDV { get; set; }
        public string DONVITINH { get; set; }
        public decimal DONGIA { get; set; }
        public int SOLUONGTON { get; set; }
        public string TRANGTHAIKD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDICHVUDAT> CHITIETDICHVUDAT { get; set; }
    }
}
