//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanPickleball_65132651.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string SOHD { get; set; }
        public string MAPHIEUDAT { get; set; }
        public string MANV { get; set; }
        public System.DateTime NGAYLAP { get; set; }
        public string HINHTHUCTT { get; set; }
        public decimal TIENTHUESAN { get; set; }
        public decimal TIENDICHVU { get; set; }
        public decimal GIAMGIAHOIVIEN { get; set; }
        public decimal TONGTHANHTOAN { get; set; }
    
        public virtual PHIEUDATSAN PHIEUDATSAN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
