//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanPickleball_65132651.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOIVIEN
    {
        public string MAHOIVIEN { get; set; }
        public string MANV { get; set; }
        public string MAKH { get; set; }
        public string LOAITHE { get; set; }
        public System.DateTime NGAYBATDAU { get; set; }
        public System.DateTime NGAYKETTHUC { get; set; }
        public decimal PHIDANGKY { get; set; }
        public string TRANGTHAIPHI { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
