//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanPickleball_65132651.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.HOIVIEN = new HashSet<HOIVIEN>();
            this.PHIEUDATSAN = new HashSet<PHIEUDATSAN>();
        }
    
        public string MAKH { get; set; }
        public string HOTENKH { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        public string DIACHI { get; set; }
        public string SODIENTHOAIKH { get; set; }
        public string EMAILKH { get; set; }
        public string MATKHAUKH { get; set; }
        public int SOLANBUNG { get; set; }
        public string TRANGTHAITK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOIVIEN> HOIVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDATSAN> PHIEUDATSAN { get; set; }
    }
}
