//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanPickleball_65132651.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDATSAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDATSAN()
        {
            this.CHITIETDICHVUDAT = new HashSet<CHITIETDICHVUDAT>();
            this.HOADON = new HashSet<HOADON>();
        }
    
        public string MAPHIEUDAT { get; set; }
        public string MAKH { get; set; }
        public string MASAN { get; set; }
        public string MANV { get; set; }
        public System.DateTime NGAYDAT { get; set; }
        public System.TimeSpan GIOBATDAU { get; set; }
        public System.TimeSpan GIOKETTHUC { get; set; }
        public decimal TONGTIENTAMTINH { get; set; }
        public string TRANGTHAIPHIEU { get; set; }
        public string GHICHU { get; set; }
        public string TRANGTHAITHANHTOAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDICHVUDAT> CHITIETDICHVUDAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADON { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual SAN SAN { get; set; }
    }
}
