//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanPickleball_65132651.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAN()
        {
            this.PHIEUDATSAN = new HashSet<PHIEUDATSAN>();
        }
    
        public string MASAN { get; set; }
        public string MALOAISAN { get; set; }
        public string TENSAN { get; set; }
        public string TRANGTHAISAN { get; set; }
        public string MOTASAN { get; set; }
    
        public virtual LOAISAN LOAISAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDATSAN> PHIEUDATSAN { get; set; }
    }
}
