//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanPickleball_65132651.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public string MATHAMSO { get; set; }
        public string TENTHAMSO { get; set; }
        public string KIEU_DVT { get; set; }
        public string GIATRI { get; set; }
        public string TINHTRANG { get; set; }
    }
}
